# -*- coding: utf-8 -*-
"""LautonomyCosineMetrics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Xir3OjuVj3NhB2RTEAKBPx54dqHxpyT
"""

import pandas as pd
import numpy as np
from google.colab import files

df = pd.read_csv("/content/euclidean_similarity.csv", index_col = 0)
df.shape

anchor_points = df.columns.to_list()
anchor_points = list(map(int, anchor_points))
len(anchor_points)

with open("/content/unres_embeddings.txt") as original:
    lines = original.readlines()


count = 0
index = 0
for line in lines:
    if count % 2 != 0:
        if index not in anchor_points:
            lines[count] = line[:-2] + '0\n'
        index += 1
    count += 1
print(lines[anchor_points[0] + 3])

len(lines)

with open('untitled', 'w') as f:
    for line in lines:
        f.write(line)



anchor_words = []
with open("/content/untitled") as f:
    lines = f.readlines()

for nbr_line, line in enumerate(lines):
    if line.endswith(' 1\n'):
        output_line = lines[nbr_line - 1] # !!! nbr_line - 4 may be < 0
        anchor_words.append(output_line[:-1])

len(anchor_words)

meta = pd.DataFrame(anchor_words, columns=[""])
anchor_points.sort(reverse = False)
meta.index = anchor_points
meta

meta.to_csv('meta-main.txt', header = False, sep = ' ')
files.download('meta-main.txt')

len(anchor_words)

count = 0
with open("/content/fixed_updated_original.txt") as fil:
    for line in lines:
        if line.endswith(' 1\n'):
            count += 1
print(count)



count

import os
!mkdir anchor_txt_files_EUCLIDEAN
os.chdir('anchor_txt_files_EUCLIDEAN')
!pwd

os.chdir('..')

!pwd

for anchor in anchor_points:
    test = df[str(anchor)].abs().sort_values(ascending=[False])
    test.to_csv(str(anchor) + '.txt', header=False)
    files.download(str(anchor) + '.txt')

!cp -r "/content/anchor_txt_files_EUCLIDEAN" "/content/drive/MyDrive"